name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - run: bun install --no-save
      - run: bun run setup-ci
      - run: bun run type-check
      - run: bun run lint
      - run: bun test
      - run: bun run build
      - run: bun run zip
